-- 056_activation_package.sql
--
-- ============================================================================
-- NOT EXECUTED. Authored and reviewed only. Disposable-cluster verification
-- only. GENERATED by scripts/emit-activation-migration.ts — do not hand-edit;
-- re-run the generator and review the diff.
-- ============================================================================
--
-- ONE ATOMIC TRANSACTION carrying the whole activation package:
--   1. schema      kg_product.support_state (known | reserve | supported)
--   2. data        additive verified music brands + products (known/private)
--   3. promotion   exactly the frozen 48 -> supported
--   4. assertion   final state proven BEFORE COMMIT
--
-- WHY ONE FILE. The earlier split (056 schema + 057 data + a psql wrapper)
-- could commit a state with ZERO supported products: correct-but-inert, and
-- invisible because the matcher fails closed. Nothing was ever deployed, so the
-- package is renumbered and consolidated instead of patched. There is now no
-- intermediate commit at all — any failed predicate aborts the single
-- transaction and leaves PRE untouched.
--
-- WHAT IT DELIBERATELY DOES NOT DO
--   * No UPDATE to browse_visibility  -> nothing is published.
--   * No UPDATE to tier               -> no marketplace query set changes.
--   * No UPDATE to status             -> no identity or history moves.
--   * No UPDATE to attributes/images/slug -> product-owned content untouched.
--   * No broad importer run. The additive rows below ARE the production path;
--     data/knowledge-graph.json remains the clean-import source of truth.
--
-- CONFLICT SEMANTICS. A pre-existing slug is reused ONLY if it is the same
-- entity (same brand + same canonical name). A slug held by a DIFFERENT entity
-- aborts as DRIFT rather than overwriting product-owned data.
--
-- THREE-STATE CONTRACT: PRE -> apply | POST -> successful no-op | DRIFT -> abort.
-- REVERSAL: scripts/migrations/056_rollback.sql

BEGIN;

SET LOCAL statement_timeout = '300s';

-- ── inputs, as temp tables so every predicate can be checked before writing ──
CREATE TEMP TABLE _add_brand(key text PRIMARY KEY, name text NOT NULL) ON COMMIT DROP;
INSERT INTO _add_brand(key, name) VALUES
  ('ampeg', 'Ampeg'),
  ('boss', 'Boss'),
  ('burny', 'Burny'),
  ('eastman', 'Eastman'),
  ('electro-harmonix', 'Electro-Harmonix'),
  ('epiphone', 'Epiphone'),
  ('fender', 'Fender'),
  ('fernandes', 'Fernandes'),
  ('gibson', 'Gibson'),
  ('greco', 'Greco'),
  ('gretsch', 'Gretsch'),
  ('guild', 'Guild'),
  ('heritage', 'Heritage'),
  ('hofner', 'Höfner'),
  ('ibanez', 'Ibanez'),
  ('klon', 'Klon'),
  ('korg', 'Korg'),
  ('marshall', 'Marshall'),
  ('martin', 'Martin'),
  ('mesa-boogie', 'Mesa/Boogie'),
  ('music-man', 'Music Man'),
  ('mxr', 'MXR'),
  ('nash', 'Nash'),
  ('pro-co', 'Pro Co'),
  ('prs', 'PRS'),
  ('rickenbacker', 'Rickenbacker'),
  ('squier', 'Squier'),
  ('sterling', 'Sterling'),
  ('suhr', 'Suhr'),
  ('takamine', 'Takamine'),
  ('taylor', 'Taylor'),
  ('tokai', 'Tokai'),
  ('vox', 'Vox'),
  ('yamaha', 'Yamaha');

CREATE TEMP TABLE _add_product(slug text PRIMARY KEY, name text NOT NULL, model text, brand_key text NOT NULL) ON COMMIT DROP;
INSERT INTO _add_product(slug, name, model, brand_key) VALUES
  ('ampeg-b-15', 'Ampeg B-15', 'B-15', 'ampeg'),
  ('ampeg-svt', 'Ampeg SVT', 'SVT', 'ampeg'),
  ('boss-bd-2', 'Boss BD-2', 'BD-2', 'boss'),
  ('boss-ce-1', 'Boss CE-1', 'CE-1', 'boss'),
  ('boss-ce-2', 'Boss CE-2', 'CE-2', 'boss'),
  ('boss-ce-2w', 'Boss CE-2W', 'CE-2W', 'boss'),
  ('boss-dm-2', 'Boss DM-2', 'DM-2', 'boss'),
  ('boss-dm-2w', 'Boss DM-2W', 'DM-2W', 'boss'),
  ('boss-od-1', 'Boss OD-1', 'OD-1', 'boss'),
  ('boss-ph-1', 'Boss PH-1', 'PH-1', 'boss'),
  ('boss-ph-1r', 'Boss PH-1R', 'PH-1R', 'boss'),
  ('boss-sd-1', 'Boss SD-1', 'SD-1', 'boss'),
  ('burny-super-grade', 'Burny Super Grade', 'Super Grade', 'burny'),
  ('eastman-sb59', 'Eastman SB59', 'SB59', 'eastman'),
  ('ehx-big-muff-pi-current', 'EHX Big Muff Pi (current)', 'EHX Big Muff Pi (current)', 'electro-harmonix'),
  ('ehx-big-muff-pi-op-amp', 'EHX Big Muff Pi Op-Amp', 'EHX Big Muff Pi Op-Amp', 'electro-harmonix'),
  ('ehx-big-muff-pi-ram-s-head', 'EHX Big Muff Pi Ram''s Head', 'EHX Big Muff Pi Ram''s Head', 'electro-harmonix'),
  ('ehx-big-muff-pi-russian', 'EHX Big Muff Pi Russian', 'EHX Big Muff Pi Russian', 'electro-harmonix'),
  ('ehx-big-muff-pi-triangle', 'EHX Big Muff Pi Triangle', 'EHX Big Muff Pi Triangle', 'electro-harmonix'),
  ('ehx-deluxe-memory-man-1100-tt', 'EHX Deluxe Memory Man 1100-TT', 'EHX Deluxe Memory Man 1100-TT', 'electro-harmonix'),
  ('ehx-deluxe-memory-man-550-tt', 'EHX Deluxe Memory Man 550-TT', 'EHX Deluxe Memory Man 550-TT', 'electro-harmonix'),
  ('ehx-deluxe-memory-man-vintage-mn3005', 'EHX Deluxe Memory Man (vintage MN3005)', 'EHX Deluxe Memory Man (vintage MN3005)', 'electro-harmonix'),
  ('ehx-deluxe-memory-man-xo', 'EHX Deluxe Memory Man XO', 'EHX Deluxe Memory Man XO', 'electro-harmonix'),
  ('ehx-memory-man-nano', 'EHX Memory Man Nano', 'EHX Memory Man Nano', 'electro-harmonix'),
  ('epiphone-casino', 'Epiphone Casino', 'Casino', 'epiphone'),
  ('fender-65-deluxe-reverb-reissue', 'Fender ''65 Deluxe Reverb Reissue', '''65 Deluxe Reverb Reissue', 'fender'),
  ('fender-65-princeton-reverb-reissue', 'Fender ''65 Princeton Reverb Reissue', '''65 Princeton Reverb Reissue', 'fender'),
  ('fender-65-twin-reverb-reissue', 'Fender ''65 Twin Reverb Reissue', '''65 Twin Reverb Reissue', 'fender'),
  ('fender-68-custom-deluxe-reverb', 'Fender ''68 Custom Deluxe Reverb', '''68 Custom Deluxe Reverb', 'fender'),
  ('fender-american-professional-ii-stratocaster', 'Fender American Professional II Stratocaster', 'American Professional II Stratocaster', 'fender'),
  ('fender-american-standard-jazz-bass', 'Fender American Standard Jazz Bass', 'American Standard Jazz Bass', 'fender'),
  ('fender-american-standard-precision-bass', 'Fender American Standard Precision Bass', 'American Standard Precision Bass', 'fender'),
  ('fender-american-standard-telecaster', 'Fender American Standard Telecaster', 'American Standard Telecaster', 'fender'),
  ('fender-american-ultra-stratocaster', 'Fender American Ultra Stratocaster', 'American Ultra Stratocaster', 'fender'),
  ('fender-american-vintage-52-telecaster', 'Fender American Vintage ''52 Telecaster', 'American Vintage ''52 Telecaster', 'fender'),
  ('fender-american-vintage-ii-jazzmaster', 'Fender American Vintage II Jazzmaster', 'American Vintage II Jazzmaster', 'fender'),
  ('fender-american-vintage-ii-stratocaster', 'Fender American Vintage II Stratocaster', 'American Vintage II Stratocaster', 'fender'),
  ('fender-deluxe-reverb-vintage', 'Fender Deluxe Reverb (vintage)', 'Deluxe Reverb (vintage)', 'fender'),
  ('fender-kurt-cobain-jaguar', 'Fender Kurt Cobain Jaguar', 'Kurt Cobain Jaguar', 'fender'),
  ('fender-player-stratocaster', 'Fender Player Stratocaster', 'Player Stratocaster', 'fender'),
  ('fender-precision-bass-57-reissue', 'Fender Precision Bass ''57 Reissue', 'Precision Bass ''57 Reissue', 'fender'),
  ('fender-princeton-reverb-vintage', 'Fender Princeton Reverb (vintage)', 'Princeton Reverb (vintage)', 'fender'),
  ('fender-telecaster-custom', 'Fender Telecaster Custom', 'Telecaster Custom', 'fender'),
  ('fender-telecaster-deluxe', 'Fender Telecaster Deluxe', 'Telecaster Deluxe', 'fender'),
  ('fender-telecaster-thinline', 'Fender Telecaster Thinline', 'Telecaster Thinline', 'fender'),
  ('fender-tone-master-deluxe-reverb', 'Fender Tone Master Deluxe Reverb', 'Tone Master Deluxe Reverb', 'fender'),
  ('fender-tone-master-princeton-reverb', 'Fender Tone Master Princeton Reverb', 'Tone Master Princeton Reverb', 'fender'),
  ('fender-tone-master-twin-reverb', 'Fender Tone Master Twin Reverb', 'Tone Master Twin Reverb', 'fender'),
  ('fender-troy-van-leeuwen-jazzmaster', 'Fender Troy Van Leeuwen Jazzmaster', 'Troy Van Leeuwen Jazzmaster', 'fender'),
  ('fender-twin-reverb-vintage', 'Fender Twin Reverb (vintage)', 'Twin Reverb (vintage)', 'fender'),
  ('fernandes-the-function', 'Fernandes The Function', 'The Function', 'fernandes'),
  ('gibson-custom-shop-les-paul-r0', 'Gibson Custom Shop Les Paul R0', 'Custom Shop Les Paul R0', 'gibson'),
  ('gibson-custom-shop-les-paul-r7', 'Gibson Custom Shop Les Paul R7', 'Custom Shop Les Paul R7', 'gibson'),
  ('gibson-custom-shop-les-paul-r8', 'Gibson Custom Shop Les Paul R8', 'Custom Shop Les Paul R8', 'gibson'),
  ('gibson-custom-shop-les-paul-r9', 'Gibson Custom Shop Les Paul R9', 'Custom Shop Les Paul R9', 'gibson'),
  ('gibson-es-330', 'Gibson ES-330', 'ES-330', 'gibson'),
  ('gibson-es-335-block', 'Gibson ES-335 Block', 'ES-335 Block', 'gibson'),
  ('gibson-es-335-dot', 'Gibson ES-335 Dot', 'ES-335 Dot', 'gibson'),
  ('gibson-es-345', 'Gibson ES-345', 'ES-345', 'gibson'),
  ('gibson-es-355', 'Gibson ES-355', 'ES-355', 'gibson'),
  ('gibson-explorer', 'Gibson Explorer', 'Explorer', 'gibson'),
  ('gibson-firebird', 'Gibson Firebird', 'Firebird', 'gibson'),
  ('gibson-flying-v', 'Gibson Flying V', 'Flying V', 'gibson'),
  ('gibson-les-paul-junior', 'Gibson Les Paul Junior', 'Les Paul Junior', 'gibson'),
  ('gibson-les-paul-special', 'Gibson Les Paul Special', 'Les Paul Special', 'gibson'),
  ('gibson-les-paul-standard-50s', 'Gibson Les Paul Standard ''50s', 'Les Paul Standard ''50s', 'gibson'),
  ('gibson-les-paul-standard-60s', 'Gibson Les Paul Standard ''60s', 'Les Paul Standard ''60s', 'gibson'),
  ('gibson-les-paul-studio', 'Gibson Les Paul Studio', 'Les Paul Studio', 'gibson'),
  ('gibson-sg-61-reissue', 'Gibson SG 61 Reissue', 'SG 61 Reissue', 'gibson'),
  ('gibson-thunderbird', 'Gibson Thunderbird', 'Thunderbird', 'gibson'),
  ('greco-mint-collection', 'Greco Mint Collection', 'Mint Collection', 'greco'),
  ('greco-spacey-sound', 'Greco Spacey Sound', 'Spacey Sound', 'greco'),
  ('greco-super-real', 'Greco Super Real', 'Super Real', 'greco'),
  ('gretsch-country-gentleman', 'Gretsch Country Gentleman', 'Country Gentleman', 'gretsch'),
  ('gretsch-duo-jet', 'Gretsch Duo Jet', 'Duo Jet', 'gretsch'),
  ('gretsch-g5420t-electromatic', 'Gretsch G5420T Electromatic', 'G5420T Electromatic', 'gretsch'),
  ('gretsch-g6120-chet-atkins', 'Gretsch G6120 Chet Atkins', 'G6120 Chet Atkins', 'gretsch'),
  ('gretsch-g6136-white-falcon', 'Gretsch G6136 White Falcon', 'G6136 White Falcon', 'gretsch'),
  ('guild-d-55', 'Guild D-55', 'D-55', 'guild'),
  ('heritage-h-150', 'Heritage H-150', 'H-150', 'heritage'),
  ('heritage-h-535', 'Heritage H-535', 'H-535', 'heritage'),
  ('hofner-500-1-german-reissue', 'Höfner 500/1 German Reissue', '500/1 German Reissue', 'hofner'),
  ('hofner-contemporary-h500-1', 'Höfner Contemporary H500/1', 'Contemporary H500/1', 'hofner'),
  ('hofner-ignition-hi-bb', 'Höfner Ignition HI-BB', 'Ignition HI-BB', 'hofner'),
  ('ibanez-jem777', 'Ibanez JEM777', 'JEM777', 'ibanez'),
  ('ibanez-jem7v', 'Ibanez JEM7V', 'JEM7V', 'ibanez'),
  ('ibanez-jemjr', 'Ibanez JEMJR', 'JEMJR', 'ibanez'),
  ('ibanez-rg421', 'Ibanez RG421', 'RG421', 'ibanez'),
  ('ibanez-rg550-genesis', 'Ibanez RG550 Genesis', 'RG550 Genesis', 'ibanez'),
  ('ibanez-ts808', 'Ibanez TS808', 'TS808', 'ibanez'),
  ('ibanez-ts9', 'Ibanez TS9', 'TS9', 'ibanez'),
  ('klon-centaur', 'Klon Centaur', 'Centaur', 'klon'),
  ('klon-ktr', 'Klon KTR', 'KTR', 'klon'),
  ('korg-sdd-3000-pedal', 'Korg SDD-3000 Pedal', 'SDD-3000 Pedal', 'korg'),
  ('korg-sdd-3000-rackmount', 'Korg SDD-3000 (rackmount)', 'SDD-3000 (rackmount)', 'korg'),
  ('marshall-jcm800-2203', 'Marshall JCM800 2203', 'JCM800 2203', 'marshall'),
  ('marshall-jcm800-2204', 'Marshall JCM800 2204', 'JCM800 2204', 'marshall'),
  ('marshall-jtm45', 'Marshall JTM45', 'JTM45', 'marshall'),
  ('marshall-super-lead-plexi', 'Marshall Super Lead / Plexi', 'Super Lead / Plexi', 'marshall'),
  ('martin-0-18', 'Martin 0-18', '0-18', 'martin'),
  ('martin-00-18', 'Martin 00-18', '00-18', 'martin'),
  ('martin-000-18', 'Martin 000-18', '000-18', 'martin'),
  ('martin-000-28', 'Martin 000-28', '000-28', 'martin'),
  ('martin-d-18', 'Martin D-18', 'D-18', 'martin'),
  ('martin-hd-28', 'Martin HD-28', 'HD-28', 'martin'),
  ('martin-om-28', 'Martin OM-28', 'OM-28', 'martin'),
  ('mesa-boogie-dual-rectifier', 'Mesa/Boogie Dual Rectifier', 'Dual Rectifier', 'mesa-boogie'),
  ('mesa-boogie-mark-iic', 'Mesa/Boogie Mark IIC+', 'Mark IIC+', 'mesa-boogie'),
  ('music-man-stingray-usa', 'Music Man StingRay (USA)', 'StingRay (USA)', 'music-man'),
  ('mxr-phase-90', 'MXR Phase 90', 'Phase 90', 'mxr'),
  ('nash-j-model', 'Nash J-Model', 'J-Model', 'nash'),
  ('nash-pb-model', 'Nash PB-Model', 'PB-Model', 'nash'),
  ('nash-s-model', 'Nash S-Model', 'S-Model', 'nash'),
  ('nash-t-model', 'Nash T-Model', 'T-Model', 'nash'),
  ('pro-co-rat-rat2', 'Pro Co RAT / RAT2', 'RAT / RAT2', 'pro-co'),
  ('prs-custom-22', 'PRS Custom 22', 'Custom 22', 'prs'),
  ('prs-custom-24', 'PRS Custom 24', 'Custom 24', 'prs'),
  ('prs-mccarty-594', 'PRS McCarty 594', 'McCarty 594', 'prs'),
  ('prs-silver-sky', 'PRS Silver Sky', 'Silver Sky', 'prs'),
  ('rickenbacker-360-12', 'Rickenbacker 360/12', '360/12', 'rickenbacker'),
  ('rickenbacker-4001', 'Rickenbacker 4001', '4001', 'rickenbacker'),
  ('rickenbacker-4003', 'Rickenbacker 4003', '4003', 'rickenbacker'),
  ('squier-classic-vibe-stratocaster', 'Squier Classic Vibe Stratocaster', 'Classic Vibe Stratocaster', 'squier'),
  ('squier-j-mascis-jazzmaster', 'Squier J Mascis Jazzmaster', 'J Mascis Jazzmaster', 'squier'),
  ('sterling-by-music-man', 'Sterling by Music Man', 'by Music Man', 'sterling'),
  ('suhr-classic-s', 'Suhr Classic S', 'Classic S', 'suhr'),
  ('suhr-classic-t', 'Suhr Classic T', 'Classic T', 'suhr'),
  ('takamine-f-360s', 'Takamine F-360S', 'F-360S', 'takamine'),
  ('taylor-314ce', 'Taylor 314ce', '314ce', 'taylor'),
  ('taylor-814ce', 'Taylor 814ce', '814ce', 'taylor'),
  ('taylor-gs-mini', 'Taylor GS Mini', 'GS Mini', 'taylor'),
  ('tokai-breezy-sound', 'Tokai Breezy Sound', 'Breezy Sound', 'tokai'),
  ('tokai-love-rock', 'Tokai Love Rock', 'Love Rock', 'tokai'),
  ('tokai-springy-sound', 'Tokai Springy Sound', 'Springy Sound', 'tokai'),
  ('vox-ac30-vintage', 'Vox AC30 (vintage)', 'AC30 (vintage)', 'vox'),
  ('yamaha-bb1200', 'Yamaha BB1200', 'BB1200', 'yamaha'),
  ('yamaha-bb2000', 'Yamaha BB2000', 'BB2000', 'yamaha'),
  ('yamaha-bb3000', 'Yamaha BB3000', 'BB3000', 'yamaha'),
  ('yamaha-bb434', 'Yamaha BB434', 'BB434', 'yamaha'),
  ('yamaha-bb734a', 'Yamaha BB734A', 'BB734A', 'yamaha'),
  ('yamaha-bbp34', 'Yamaha BBP34', 'BBP34', 'yamaha'),
  ('yamaha-sg-2000', 'Yamaha SG-2000', 'SG-2000', 'yamaha');

CREATE TEMP TABLE _frozen(slug text PRIMARY KEY) ON COMMIT DROP;
INSERT INTO _frozen(slug) VALUES
  ('emu-sp-1200'),
  ('fender-american-professional-ii-stratocaster'),
  ('fender-american-vintage-52-telecaster'),
  ('fender-mustang-bass'),
  ('fender-telecaster-custom'),
  ('fender-telecaster-thinline'),
  ('gibson-es-335-dot'),
  ('gibson-hummingbird'),
  ('gibson-j-45'),
  ('gibson-les-paul-custom'),
  ('gibson-les-paul-special'),
  ('gibson-les-paul-standard-50s'),
  ('gibson-les-paul-standard-60s'),
  ('gibson-les-paul-studio'),
  ('gibson-sg-standard-large-guard-with-maestro-vibrola'),
  ('gibson-sj-200-original'),
  ('korg-mono-poly'),
  ('korg-ms-20'),
  ('korg-polysix'),
  ('manley-voxbox'),
  ('martin-d-28'),
  ('moog-minimoog'),
  ('moog-model-d'),
  ('moog-source'),
  ('neumann-u87ai'),
  ('neve-portico-ii-master-buss-processor'),
  ('rhodes-mark-i-stage-73'),
  ('rhodes-mark-i-suitcase-73'),
  ('rhodes-mark-ii-stage-73'),
  ('roland-juno-106'),
  ('roland-juno-6'),
  ('roland-juno-60'),
  ('roland-jupiter-4'),
  ('roland-jupiter-8'),
  ('roland-re-201'),
  ('roland-re-501'),
  ('roland-sh-101'),
  ('roland-system-100'),
  ('roland-tr-606'),
  ('roland-tr-707'),
  ('roland-tr-808'),
  ('roland-tr-909'),
  ('sequential-prophet-10'),
  ('tube-tech-cl1b'),
  ('tube-tech-lca-2b'),
  ('ua-1176ln'),
  ('wurlitzer-200a'),
  ('yamaha-dx7');

DO $$
DECLARE
  v_col int; v_supported int; v_outside int; v_conflict int; v_state text; v_detail text;
  v_music_cat uuid;
BEGIN
  SELECT count(*) INTO v_col FROM information_schema.columns
   WHERE table_schema='public' AND table_name='kg_product' AND column_name='support_state';

  IF (SELECT count(*) FROM _frozen) <> 48 THEN
    RAISE EXCEPTION '056 ABORT: frozen manifest holds % slugs, expected exactly 48.', (SELECT count(*) FROM _frozen);
  END IF;

  SELECT id INTO v_music_cat FROM kg_category WHERE slug='music-gear' AND parent_id IS NULL;
  IF v_music_cat IS NULL THEN
    RAISE EXCEPTION '056 ABORT: root category music-gear not found.';
  END IF;

  -- A slug already held by a DIFFERENT entity is drift, never an overwrite.
  SELECT count(*) INTO v_conflict
    FROM _add_product a JOIN kg_product p ON p.slug = a.slug
    JOIN kg_brand b ON b.id = p.brand_id
   WHERE lower(btrim(p.canonical_name)) IS DISTINCT FROM lower(btrim(a.name));
  IF v_conflict > 0 THEN
    SELECT string_agg(a.slug, ', ' ORDER BY a.slug) INTO v_detail
      FROM _add_product a JOIN kg_product p ON p.slug = a.slug
     WHERE lower(btrim(p.canonical_name)) IS DISTINCT FROM lower(btrim(a.name));
    RAISE EXCEPTION '056 ABORT: state=DRIFT. % slug(s) are held by a different entity: %', v_conflict, v_detail;
  END IF;

  IF v_col = 0 THEN
    v_state := 'PRE';
  ELSE
    SELECT count(*) INTO v_supported FROM kg_product WHERE support_state='supported';
    SELECT count(*) INTO v_outside FROM kg_product p
      WHERE p.support_state='supported' AND NOT EXISTS (SELECT 1 FROM _frozen f WHERE f.slug=p.slug);
    IF v_supported = 48 AND v_outside = 0 THEN v_state := 'POST';
    ELSE v_state := 'DRIFT'; END IF;
  END IF;

  IF v_state = 'POST' THEN
    RAISE NOTICE '056: state=POST — schema, data and the frozen 48 are already in place. No-op.';
    RETURN;
  END IF;
  IF v_state = 'DRIFT' THEN
    RAISE EXCEPTION '056 ABORT: state=DRIFT. support_state exists with % supported product(s), % outside the frozen cohort.', v_supported, v_outside;
  END IF;
  RAISE NOTICE '056: state=PRE — applying schema, % brand(s), % product(s), then promoting 48.',
    (SELECT count(*) FROM _add_brand), (SELECT count(*) FROM _add_product);
END $$;

-- ── 1. schema ───────────────────────────────────────────────────────────────
ALTER TABLE kg_product ADD COLUMN IF NOT EXISTS support_state text NOT NULL DEFAULT 'known';

COMMENT ON COLUMN kg_product.support_state IS
  'Support axis, independent of status (identity), browse_visibility (public exposure) and tier (editorial). known = verified music identity, not a matcher target. reserve = scored candidate outside launch. supported = frozen launch cohort, IS a matcher target. Matcher eligibility is status=''active'' AND support_state=''supported''.';

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.kg_product'::regclass
                  AND conname='kg_product_support_state_check') THEN
    ALTER TABLE kg_product ADD CONSTRAINT kg_product_support_state_check
      CHECK (support_state IN ('known','reserve','supported'));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_kg_product_support_state
  ON kg_product (support_state, status) WHERE support_state = 'supported';

-- ── 2. additive data ────────────────────────────────────────────────────────
-- Brands first. ON CONFLICT DO NOTHING: an existing brand is reused as-is; no
-- product-owned attribute of an existing row is ever overwritten.
INSERT INTO kg_brand (id, name, slug, category_id)
SELECT gen_random_uuid(), a.name, a.key, (SELECT id FROM kg_category WHERE slug='music-gear' AND parent_id IS NULL)
FROM _add_brand a
ON CONFLICT (slug) DO NOTHING;

-- Products at the SAFE DEFAULT: active identity, support 'known', private,
-- editorial tier 'standard' (which is outside every scraper selector).
INSERT INTO kg_product (id, slug, canonical_name, model_name, brand_id, category_id,
                        status, support_state, browse_visibility, tier)
SELECT gen_random_uuid(), a.slug, a.name, NULLIF(a.model,''), b.id, b.category_id,
       'active', 'known', 'qa_only', 'standard'
FROM _add_product a JOIN kg_brand b ON b.slug = a.brand_key
ON CONFLICT (slug) DO NOTHING;

-- ── 3. promotion ────────────────────────────────────────────────────────────
UPDATE kg_product p SET support_state = 'supported'
  FROM _frozen f
 WHERE p.slug = f.slug AND p.status = 'active' AND p.support_state IS DISTINCT FROM 'supported';

-- ── 4. assertions, BEFORE COMMIT ────────────────────────────────────────────
DO $$
DECLARE v_missing text; v_n int; v_outside int;
BEGIN
  SELECT string_agg(f.slug, ', ' ORDER BY f.slug) INTO v_missing
    FROM _frozen f LEFT JOIN kg_product p ON p.slug=f.slug WHERE p.id IS NULL;
  IF v_missing IS NOT NULL THEN
    RAISE EXCEPTION '056 ABORT: frozen product(s) absent after the additive step: %', v_missing;
  END IF;

  SELECT count(*) INTO v_n FROM kg_product WHERE support_state='supported';
  SELECT count(*) INTO v_outside FROM kg_product p
    WHERE p.support_state='supported' AND NOT EXISTS (SELECT 1 FROM _frozen f WHERE f.slug=p.slug);
  IF v_n <> 48 OR v_outside > 0 THEN
    RAISE EXCEPTION '056 ABORT: post-condition failed — % supported (% outside the cohort), expected exactly 48/0. Transaction rolled back; no zero-target state is committed.', v_n, v_outside;
  END IF;

  -- Additive rows must never have arrived supported, public or monitored.
  SELECT count(*) INTO v_n FROM kg_product p JOIN _add_product a ON a.slug=p.slug
   WHERE (p.support_state='supported' AND NOT EXISTS (SELECT 1 FROM _frozen f WHERE f.slug=p.slug))
      OR p.browse_visibility='public' OR p.tier IN ('legendary','classic');
  IF v_n > 0 THEN
    RAISE EXCEPTION '056 ABORT: % additive product(s) are public, monitored or wrongly supported.', v_n;
  END IF;

  RAISE NOTICE '056: committed — 48 supported/private, additive rows known/private/unmonitored, visibility and tier untouched.';
END $$;

COMMIT;
