/**
 * scripts/emit-activation-migration.ts
 *
 * Generates scripts/migrations/056_activation_package.sql — the SINGLE atomic
 * migration that carries schema, additive KG data and the frozen-cohort
 * promotion. READ-ONLY: no database connection, no network. Deterministic.
 *
 *   npx tsx scripts/emit-activation-migration.ts
 *   npx tsx scripts/emit-activation-migration.ts --validate
 */
import * as fs from 'fs'
import * as path from 'path'

const ROOT = path.resolve(__dirname, '..')
const VALIDATE = process.argv.includes('--validate')
const OUT = 'scripts/migrations/056_activation_package.sql'

function parseCsv(text: string): string[][] {
  const rows: string[][] = []; let row: string[] = [], cur = '', q = false
  for (let i = 0; i < text.length; i++) { const c = text[i]
    if (q) { if (c === '"') { if (text[i+1] === '"') { cur += '"'; i++ } else q = false } else cur += c }
    else if (c === '"') q = true
    else if (c === ',') { row.push(cur); cur = '' }
    else if (c === '\n') { row.push(cur); rows.push(row); row = []; cur = '' }
    else if (c !== '\r') cur += c }
  if (cur !== '' || row.length) { row.push(cur); rows.push(row) }
  return rows.filter(r => r.some(c => c.trim() !== ''))
}
const read = (rel: string) => { const rows = parseCsv(fs.readFileSync(path.join(ROOT, rel), 'utf8')); const h = rows[0]
  return rows.slice(1).map(r => Object.fromEntries(h.map((k, i) => [k, r[i] ?? ''])) as Record<string,string>) }
const lit = (s: string) => "'" + String(s).replace(/'/g, "''") + "'"

const disp = read('data/klup-candidate-disposition.csv')
const cohort = read('data/klup-launch-cohort-frozen.csv')
const seed = JSON.parse(fs.readFileSync(path.join(ROOT, 'data/knowledge-graph.json'), 'utf8'))
const brands: Record<string, { products: Record<string, any> }> = seed.categories['music-gear'].brands

// Additive set = every product the disposition ledger says we added to the seed.
const adds = disp.filter(d => d.outcome === 'added_verified_kg_product' && d.seed_slug)
const bySlug = new Map<string, { brand: string; slug: string; name: string; model: string }>()
for (const a of adds) {
  const p = brands[a.seed_brand]?.products?.[a.seed_slug]
  if (!p) continue
  bySlug.set(a.seed_slug, { brand: a.seed_brand, slug: a.seed_slug, name: p.name, model: p.model ?? '' })
}
const brandNames = new Map<string, string>()
for (const a of Array.from(bySlug.values())) {
  const src = disp.find(d => d.seed_slug === a.slug)
  if (src) brandNames.set(a.brand, src.brand)
}
// The 48 frozen slugs.
const SEED_SLUG: Record<string,string> = {
 'Fender American Professional II Stratocaster':'fender-american-professional-ii-stratocaster',
 'Fender Telecaster Thinline':'fender-telecaster-thinline','Fender Telecaster Custom':'fender-telecaster-custom',
 "Fender American Vintage '52 Telecaster":'fender-american-vintage-52-telecaster',
 "Gibson Les Paul Standard '50s":'gibson-les-paul-standard-50s',"Gibson Les Paul Standard '60s":'gibson-les-paul-standard-60s',
 'Gibson Les Paul Studio':'gibson-les-paul-studio','Gibson Les Paul Special':'gibson-les-paul-special',
 'Gibson ES-335 Dot':'gibson-es-335-dot',
}
const frozen = cohort.map(c => c.slug || SEED_SLUG[c.canonical_title]).filter(Boolean).sort()
if (frozen.length !== 48) { console.error(`frozen cohort resolved to ${frozen.length}, expected 48`); process.exit(1) }

const brandRows = Array.from(brandNames.entries()).sort((a,b)=>a[0].localeCompare(b[0]))
  .map(([k,n]) => `  (${lit(k)}, ${lit(n)})`).join(',\n')
const productRows = Array.from(bySlug.values()).sort((a,b)=>a.slug.localeCompare(b.slug))
  .map(p => `  (${lit(p.slug)}, ${lit(p.name)}, ${lit(p.model)}, ${lit(p.brand)})`).join(',\n')
const frozenRows = frozen.map(s => `  (${lit(s)})`).join(',\n')

const sql = `-- 056_activation_package.sql
--
-- ============================================================================
-- NOT EXECUTED. Authored and reviewed only. Disposable-cluster verification
-- only. GENERATED by scripts/emit-activation-migration.ts — do not hand-edit;
-- re-run the generator and review the diff.
-- ============================================================================
--
-- ONE ATOMIC TRANSACTION carrying the whole activation package:
--   1. schema      kg_product.support_state (known | reserve | supported)
--   2. data        additive verified music brands + products (known/private)
--   3. promotion   exactly the frozen 48 -> supported
--   4. assertion   final state proven BEFORE COMMIT
--
-- WHY ONE FILE. The earlier split (056 schema + 057 data + a psql wrapper)
-- could commit a state with ZERO supported products: correct-but-inert, and
-- invisible because the matcher fails closed. Nothing was ever deployed, so the
-- package is renumbered and consolidated instead of patched. There is now no
-- intermediate commit at all — any failed predicate aborts the single
-- transaction and leaves PRE untouched.
--
-- WHAT IT DELIBERATELY DOES NOT DO
--   * No UPDATE to browse_visibility  -> nothing is published.
--   * No UPDATE to tier               -> no marketplace query set changes.
--   * No UPDATE to status             -> no identity or history moves.
--   * No UPDATE to attributes/images/slug -> product-owned content untouched.
--   * No broad importer run. The additive rows below ARE the production path;
--     data/knowledge-graph.json remains the clean-import source of truth.
--
-- CONFLICT SEMANTICS. A pre-existing slug is reused ONLY if it is the same
-- entity (same brand + same canonical name). A slug held by a DIFFERENT entity
-- aborts as DRIFT rather than overwriting product-owned data.
--
-- THREE-STATE CONTRACT: PRE -> apply | POST -> successful no-op | DRIFT -> abort.
-- REVERSAL: scripts/migrations/056_rollback.sql

BEGIN;

SET LOCAL statement_timeout = '300s';

-- ── inputs, as temp tables so every predicate can be checked before writing ──
CREATE TEMP TABLE _add_brand(key text PRIMARY KEY, name text NOT NULL) ON COMMIT DROP;
INSERT INTO _add_brand(key, name) VALUES
${brandRows};

CREATE TEMP TABLE _add_product(slug text PRIMARY KEY, name text NOT NULL, model text, brand_key text NOT NULL) ON COMMIT DROP;
INSERT INTO _add_product(slug, name, model, brand_key) VALUES
${productRows};

CREATE TEMP TABLE _frozen(slug text PRIMARY KEY) ON COMMIT DROP;
INSERT INTO _frozen(slug) VALUES
${frozenRows};

DO $$
DECLARE
  v_col int; v_supported int; v_outside int; v_conflict int; v_state text; v_detail text;
  v_music_cat uuid;
BEGIN
  SELECT count(*) INTO v_col FROM information_schema.columns
   WHERE table_schema='public' AND table_name='kg_product' AND column_name='support_state';

  IF (SELECT count(*) FROM _frozen) <> 48 THEN
    RAISE EXCEPTION '056 ABORT: frozen manifest holds % slugs, expected exactly 48.', (SELECT count(*) FROM _frozen);
  END IF;

  SELECT id INTO v_music_cat FROM kg_category WHERE slug='music-gear' AND parent_id IS NULL;
  IF v_music_cat IS NULL THEN
    RAISE EXCEPTION '056 ABORT: root category music-gear not found.';
  END IF;

  -- A slug already held by a DIFFERENT entity is drift, never an overwrite.
  SELECT count(*) INTO v_conflict
    FROM _add_product a JOIN kg_product p ON p.slug = a.slug
    JOIN kg_brand b ON b.id = p.brand_id
   WHERE lower(btrim(p.canonical_name)) IS DISTINCT FROM lower(btrim(a.name));
  IF v_conflict > 0 THEN
    SELECT string_agg(a.slug, ', ' ORDER BY a.slug) INTO v_detail
      FROM _add_product a JOIN kg_product p ON p.slug = a.slug
     WHERE lower(btrim(p.canonical_name)) IS DISTINCT FROM lower(btrim(a.name));
    RAISE EXCEPTION '056 ABORT: state=DRIFT. % slug(s) are held by a different entity: %', v_conflict, v_detail;
  END IF;

  IF v_col = 0 THEN
    v_state := 'PRE';
  ELSE
    SELECT count(*) INTO v_supported FROM kg_product WHERE support_state='supported';
    SELECT count(*) INTO v_outside FROM kg_product p
      WHERE p.support_state='supported' AND NOT EXISTS (SELECT 1 FROM _frozen f WHERE f.slug=p.slug);
    IF v_supported = 48 AND v_outside = 0 THEN v_state := 'POST';
    ELSE v_state := 'DRIFT'; END IF;
  END IF;

  IF v_state = 'POST' THEN
    RAISE NOTICE '056: state=POST — schema, data and the frozen 48 are already in place. No-op.';
    RETURN;
  END IF;
  IF v_state = 'DRIFT' THEN
    RAISE EXCEPTION '056 ABORT: state=DRIFT. support_state exists with % supported product(s), % outside the frozen cohort.', v_supported, v_outside;
  END IF;
  RAISE NOTICE '056: state=PRE — applying schema, % brand(s), % product(s), then promoting 48.',
    (SELECT count(*) FROM _add_brand), (SELECT count(*) FROM _add_product);
END $$;

-- ── 1. schema ───────────────────────────────────────────────────────────────
ALTER TABLE kg_product ADD COLUMN IF NOT EXISTS support_state text NOT NULL DEFAULT 'known';

COMMENT ON COLUMN kg_product.support_state IS
  'Support axis, independent of status (identity), browse_visibility (public exposure) and tier (editorial). known = verified music identity, not a matcher target. reserve = scored candidate outside launch. supported = frozen launch cohort, IS a matcher target. Matcher eligibility is status=''active'' AND support_state=''supported''.';

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.kg_product'::regclass
                  AND conname='kg_product_support_state_check') THEN
    ALTER TABLE kg_product ADD CONSTRAINT kg_product_support_state_check
      CHECK (support_state IN ('known','reserve','supported'));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_kg_product_support_state
  ON kg_product (support_state, status) WHERE support_state = 'supported';

-- ── 2. additive data ────────────────────────────────────────────────────────
-- Brands first. ON CONFLICT DO NOTHING: an existing brand is reused as-is; no
-- product-owned attribute of an existing row is ever overwritten.
INSERT INTO kg_brand (id, name, slug, category_id)
SELECT gen_random_uuid(), a.name, a.key, (SELECT id FROM kg_category WHERE slug='music-gear' AND parent_id IS NULL)
FROM _add_brand a
ON CONFLICT (slug) DO NOTHING;

-- Products at the SAFE DEFAULT: active identity, support 'known', private,
-- editorial tier 'standard' (which is outside every scraper selector).
INSERT INTO kg_product (id, slug, canonical_name, model_name, brand_id, category_id,
                        status, support_state, browse_visibility, tier)
SELECT gen_random_uuid(), a.slug, a.name, NULLIF(a.model,''), b.id, b.category_id,
       'active', 'known', 'qa_only', 'standard'
FROM _add_product a JOIN kg_brand b ON b.slug = a.brand_key
ON CONFLICT (slug) DO NOTHING;

-- ── 3. promotion ────────────────────────────────────────────────────────────
UPDATE kg_product p SET support_state = 'supported'
  FROM _frozen f
 WHERE p.slug = f.slug AND p.status = 'active' AND p.support_state IS DISTINCT FROM 'supported';

-- ── 4. assertions, BEFORE COMMIT ────────────────────────────────────────────
DO $$
DECLARE v_missing text; v_n int; v_outside int;
BEGIN
  SELECT string_agg(f.slug, ', ' ORDER BY f.slug) INTO v_missing
    FROM _frozen f LEFT JOIN kg_product p ON p.slug=f.slug WHERE p.id IS NULL;
  IF v_missing IS NOT NULL THEN
    RAISE EXCEPTION '056 ABORT: frozen product(s) absent after the additive step: %', v_missing;
  END IF;

  SELECT count(*) INTO v_n FROM kg_product WHERE support_state='supported';
  SELECT count(*) INTO v_outside FROM kg_product p
    WHERE p.support_state='supported' AND NOT EXISTS (SELECT 1 FROM _frozen f WHERE f.slug=p.slug);
  IF v_n <> 48 OR v_outside > 0 THEN
    RAISE EXCEPTION '056 ABORT: post-condition failed — % supported (% outside the cohort), expected exactly 48/0. Transaction rolled back; no zero-target state is committed.', v_n, v_outside;
  END IF;

  -- Additive rows must never have arrived supported, public or monitored.
  SELECT count(*) INTO v_n FROM kg_product p JOIN _add_product a ON a.slug=p.slug
   WHERE (p.support_state='supported' AND NOT EXISTS (SELECT 1 FROM _frozen f WHERE f.slug=p.slug))
      OR p.browse_visibility='public' OR p.tier IN ('legendary','classic');
  IF v_n > 0 THEN
    RAISE EXCEPTION '056 ABORT: % additive product(s) are public, monitored or wrongly supported.', v_n;
  END IF;

  RAISE NOTICE '056: committed — 48 supported/private, additive rows known/private/unmonitored, visibility and tier untouched.';
END $$;

COMMIT;
`
if (VALIDATE) {
  const p = path.join(ROOT, OUT)
  if (!fs.existsSync(p) || fs.readFileSync(p, 'utf8') !== sql) {
    console.error(`activation migration out of date: ${OUT}`); process.exit(1)
  }
  console.log('activation migration reproduces exactly.')
} else {
  fs.writeFileSync(path.join(ROOT, OUT), sql)
  console.log(`wrote ${OUT}`)
}
console.log(`brands ${brandNames.size} · products ${bySlug.size} · frozen ${frozen.length}`)
