/**
 * scripts/emit-clean-import-sql.ts
 *
 * Emits SQL to stdout that reproduces what a CLEAN `npm run import-kg` does to
 * `kg_product` (status-preserving fields) and `kg_identifier`
 * (delete-everything-then-rebuild), derived from `data/knowledge-graph.json`.
 *
 * ─────────────────────────────────────────────────────────────────────────
 * WRITES NOTHING. It only prints SQL. The isolated harness pipes that SQL into
 * a DISPOSABLE local PostgreSQL cluster. It has no database client, reads no
 * connection environment variable, and is never pointed at production.
 * ─────────────────────────────────────────────────────────────────────────
 *
 * FAITHFULNESS to scripts/import-knowledge-graph.ts:
 *   * identifier derivation is the shared `deriveSeedIdentifiers` used by the
 *     importer's own `filterIdentifiers` pass
 *   * `deleteAll('kg_identifier')` then insert — same order
 *   * products absent from the database are skipped, mirroring the importer's
 *     `if (!productId) continue`
 *   * `status` is NOT written, mirroring the status-preserving upsert
 *
 * Usage:  npx tsx scripts/emit-clean-import-sql.ts > /tmp/clean-import.sql
 */

import { loadSeed, seedProducts, deriveSeedIdentifiers } from './lib/seed-identifier-manifest'

function q(s: string): string {
  return `'${String(s).replace(/'/g, "''")}'`
}

const kg = loadSeed()
const products = seedProducts(kg)
const idents = deriveSeedIdentifiers(kg)

const out: string[] = []
out.push('-- GENERATED by scripts/emit-clean-import-sql.ts — isolated verification only.')
out.push('-- Reproduces a clean importer rebuild of kg_product fields + kg_identifier.')
out.push('BEGIN;')

// 1. Product fields the seed owns. `status` is deliberately absent: the fixed
//    importer preserves whatever status a row already has, so a retired
//    duplicate stays retired.
out.push('-- product fields (status intentionally NOT written)')
for (const [slug, p] of products) {
  const model = p.model == null ? 'NULL' : q(p.model)
  out.push(
    `UPDATE kg_product SET canonical_name = ${q(p.name ?? slug)}, model_name = ${model} ` +
    `WHERE slug = ${q(slug)};`,
  )
}

// 2. The destructive rebuild.
out.push('-- kg_identifier: delete-all then rebuild (mirrors deleteAll + insertBatch)')
out.push('DELETE FROM kg_identifier;')
for (const r of idents) {
  out.push(
    `INSERT INTO kg_identifier (product_id, type, value, confidence, source) ` +
    `SELECT p.id, ${q(r.type)}, ${q(r.value)}, 80, 'seed' FROM kg_product p WHERE p.slug = ${q(r.slug)};`,
  )
}

out.push('COMMIT;')
process.stdout.write(out.join('\n') + '\n')
