/**
 * The restricted-search index.
 *
 * Stage 3 WP-4. See docs/stage-3-v1-decision-and-build-plan.md §8.4.
 *
 * THE WHOLE SUPPORTED COHORT — every matcher-eligible product, public or
 * private — plus the navigation families.
 *
 * READ FROM LIVE STATE, NOT FROM A COMMITTED FILE (PAN-147). This used to be a
 * build-time artefact, `frontend/data/klup-search-index.json`, regenerated by
 * hand. The owner changes the supported set from admin and nothing rebuilt the
 * file, so every product supported since the last regeneration was unfindable
 * (PAN-143: all 22 Boss pedals). The resolve route now builds the product
 * section from the rows `loadProductEntities()` reads, through
 * `productEntity()`, and caches the result for a short window (see the route).
 *
 * WHY THE SUPPORTED COHORT AND NOT THE PUBLIC ONE. An index of only the public
 * cohort makes the INDEX the visibility authority, so a `qa_only -> public`
 * promotion would wait for the index to refresh. Indexing the whole supported
 * cohort and filtering per request leaves visibility with the only place that
 * is always current — live catalogue state, re-read on every request.
 *
 * WHAT THE INDEX IS NOT. It is not an eligibility authority, and not a
 * visibility one. It decides only WHICH ENTITY A TERM MEANS. Whether that
 * entity may be returned is re-decided per request, uncached, by the four-axis
 * predicate in `lib/catalogue.ts` (`filterEligibleSlugs`), so the private
 * identities in here can be recognised but never returned. A stale index can
 * therefore be late to recognise a NEWLY SUPPORTED product, but can never
 * publish a private one.
 *
 * THEREFORE THIS MODULE IS SERVER-ONLY. The index carries the slugs and labels
 * of unpublished products. It is imported by `app/api/search/resolve/route.ts`
 * and by the test suite, and by nothing that ships to a browser; the guard
 * below makes an accidental client import fail loudly rather than quietly
 * bundling private catalogue state into a public chunk.
 *
 * FAMILIES ARE READ LIVE FROM REVIEWED CODE. `lib/families.ts` is not a
 * database entity; `buildSearchIndex()` derives the family section from the
 * caller's `NAVIGATION_FAMILIES`.
 */

// The `server-only` package is not a dependency and `frontend/package.json` is
// WP-5-owned, so the guard is written by hand. It runs at module scope: any
// client component that imports this module fails on first evaluation instead
// of shipping 34 private slugs to the browser.
// `globalThis`, not a bare `window`: the root tsconfig compiles this file with
// `lib: ["ES2020"]` and no DOM, so referencing `window` directly adds an eighth
// error to a baseline that is meant to stay at seven.
if (typeof (globalThis as { window?: unknown }).window !== 'undefined') {
  throw new Error(
    'lib/search-index.ts is server-only: it contains unpublished catalogue identities.',
  )
}

import type { NavigationFamily } from './families'
import { CatalogueUnavailableError, isSupportedMusicProduct } from './catalogue'
import { modelKey } from './model-key'

export type SearchEntityKind = 'product' | 'family'

export interface SearchEntity {
  kind: SearchEntityKind
  /** `/product/<slug>` for a product, `/family/<slug>` for a family. */
  slug: string
  /** Autocomplete label, carrying its disambiguating qualifier (§8.2). */
  label: string
  brand: string
  /** Accepted navigation aliases, already normalised to model keys. */
  aliasKeys: string[]
}

export interface SearchIndex {
  products: SearchEntity[]
  families: SearchEntity[]
}

/**
 * Terms that must NEVER auto-navigate, adopted verbatim from the supported-
 * search contract (selection doc §11, build plan §8.2).
 *
 * Stored as model keys so `TR 808`, `TR-808` and `tr808` are one entry. A term
 * is dangerous ON ITS OWN; the same token qualified by a brand is not. That is
 * why `minimoog` is here and `moogminimoog` is not: "Minimoog (brandless)" in
 * the contract means the bare term is ambiguous between the 1970s original and
 * the 2016 Model D reissue, while the brand-qualified form is a real identity.
 *
 * GUARDRAIL G1. `search_resolved.auto_navigated` must read exactly 0 for every
 * term in this set, for the whole release. Any dangerous term that
 * auto-navigates is a P0 correctness bug, asserted as a test rather than
 * watched as a metric.
 */
export const DANGEROUS_TERM_KEYS: ReadonlySet<string> = new Set(
  [
    // bare model families — ambiguous across several catalogue identities
    'juno',
    'jupiter',
    'prophet',
    'rhodes',
    'fenderrhodes',
    'spaceecho',
    'modeld',
    'minimoog',
    'system100',
    // bare model numbers
    '808',
    '909',
    '707',
    '727',
    '606',
    '1176',
    // bare descriptors that name a family, a control or a finish
    'poly',
    'mono',
    'source',
    'spirit',
    'synthesizer',
    'studio',
    'custom',
    'standard',
    'vintage',
    'reissue',
    'clone',
    'type',
    'style',
    // conditional forms, per the contract
    'u87', // "U 87 without Ai" — the Ai is the catalogue identity
    'cl1b', // "CL 1B (brandless)"
    'sp12', // "SP-12 when the page is SP-1200"
    'ms20mini', // "MS-20 qualified by Mini/Kit/FS"
    'ms20kit',
    'ms20fs',
  ].map((term) => modelKey(term)),
)

/**
 * Brand prefixes that must never navigate to another brand's page.
 *
 * `Squier` is Fender's budget line and `Epiphone` is Gibson's; the matcher
 * already refuses those as hard brand-collision rejections
 * (`lib/matching/match-listings.ts`), and navigation must not reintroduce what
 * matching rejects. A query carrying one of these never auto-navigates and
 * never contributes a candidate from the shadowed brand.
 */
export const SHADOW_BRAND_KEYS: ReadonlySet<string> = new Set(
  ['squier', 'epiphone', 'tokai', 'greco', 'burny'].map((term) => modelKey(term)),
)

function familyEntity(family: {
  slug: string
  label: string
  brand: string
  aliases: string[]
}): SearchEntity {
  const aliasSource = [family.label, family.slug.replace(/-/g, ' '), ...family.aliases]
  return {
    kind: 'family',
    slug: family.slug,
    label: family.label,
    brand: family.brand,
    aliasKeys: dedupeKeys(aliasSource),
  }
}

/** Normalise, drop empties, de-duplicate — the alias-key discipline. */
export function dedupeKeys(values: string[]): string[] {
  const out = new Set<string>()
  for (const value of values) {
    const key = modelKey(value)
    if (key.length > 0) out.add(key)
  }
  return Array.from(out).sort()
}

/**
 * One supported product, as `productEntity()` reads it: `kg_product` with its
 * brand embedded.
 */
export interface SearchProductRow {
  slug: string
  canonical_name: string
  model_name: string | null
  era: string | null
  year_released: number | null
  kg_brand: { name: string } | { name: string }[] | null
}

function brandOf(row: SearchProductRow): string {
  const b = Array.isArray(row.kg_brand) ? row.kg_brand[0] : row.kg_brand
  return b?.name ?? ''
}

/** `Roland RE-201 (Space Echo)` -> `Space Echo`; no parenthetical -> null. */
function parenthetical(name: string): string | null {
  const m = name.match(/\(([^)]+)\)/)
  return m ? m[1].trim() : null
}

/** `Roland RE-201 (Space Echo)` -> `Roland RE-201`. */
function withoutParenthetical(name: string): string {
  return name.replace(/\s*\([^)]*\)\s*/g, ' ').replace(/\s+/g, ' ').trim()
}

/**
 * The autocomplete label, carrying its disambiguating qualifier (§8.2).
 *
 * A qualifier is only ever taken from reviewed catalogue data — an existing
 * parenthetical, then `era`, then `year_released`. Nothing is invented: a
 * product with no qualifier in the database gets a bare label rather than a
 * plausible-looking one, because a fabricated qualifier at the point of
 * navigation is worse than none.
 */
function labelFor(row: SearchProductRow): string {
  if (parenthetical(row.canonical_name)) return row.canonical_name
  const qualifier = row.era ?? (row.year_released != null ? String(row.year_released) : null)
  return qualifier ? `${row.canonical_name} (${qualifier})` : row.canonical_name
}

/**
 * ALIASES ARE DERIVED, NEVER IMPORTED FROM THE MATCHER. `kg_identifier` and
 * `synonym` exist and are tempting, but `lib/families.ts` is explicit that
 * navigation aliases are never matcher aliases: the matcher's job is to decide
 * whether a marketplace listing IS a product, and its identifier set is tuned
 * for recall against noisy listing titles. Reusing it here would let a
 * score-70 token become a navigation target. Aliases are therefore derived
 * only from reviewed catalogue fields — brand, canonical name, model name and
 * the parenthetical qualifier — plus the hand-reviewed map in
 * `lib/synonyms.ts`.
 */
function aliasSourcesFor(row: SearchProductRow): string[] {
  const brand = brandOf(row)
  const model = row.model_name ?? ''
  const bare = withoutParenthetical(row.canonical_name)
  const paren = parenthetical(row.canonical_name)

  const sources = [
    row.slug.replace(/-/g, ' '),
    row.canonical_name,
    bare,
    model,
    brand && model ? `${brand} ${model}` : '',
    paren ?? '',
    brand && paren ? `${brand} ${paren}` : '',
  ]

  return sources.filter((s) => s.trim().length > 0)
}

/** The search entity for one supported product. */
export function productEntity(row: SearchProductRow): SearchEntity {
  return {
    kind: 'product',
    slug: row.slug,
    label: labelFor(row),
    brand: brandOf(row),
    aliasKeys: dedupeKeys(aliasSourcesFor(row)),
  }
}

/**
 * The family section, derived from reviewed code rather than from a database.
 *
 * INTEGRATION: the families are now PASSED IN rather than imported here.
 *
 * This module used to `import { NAVIGATION_FAMILIES } from './families'` at
 * module scope. `lib/search-resolver.ts` imports two constants from this file,
 * `app/search/page.tsx` is a client component that imports the resolver, and
 * `frontend/package.json` makes no `sideEffects` claim — so webpack could not
 * drop `families.ts`, and every family's `children` array rode into the client
 * bundle. That published ten `qa_only` product slugs to anonymous visitors of
 * `/search`.
 *
 * Neither package could have had that defect alone: on WP-4's base
 * `families.ts` was WP-1's empty export, and WP-2's family route is a server
 * component. It appears only when the two are combined, which is what an
 * integration pass is for.
 *
 * The dependency is now inverted and type-only. `import type` is erased, so
 * there is no module edge left to follow, and the fix does not depend on a
 * bundler successfully proving a const unused — the private data simply is not
 * in this module's graph. Callers are the server resolve route and the test,
 * both of which already hold `NAVIGATION_FAMILIES`.
 */
export function liveFamilyEntities(families: readonly NavigationFamily[]): SearchEntity[] {
  return families.map(familyEntity)
}

/**
 * The columns the index reads from `kg_product`: what `productEntity()` needs,
 * plus the two axes `isSupportedMusicProduct()` decides on.
 *
 * Never `browse_visibility`. Reading it here would invite filtering on it, and
 * that would make the index a visibility authority again (see the header).
 */
export const SEARCH_PRODUCT_SELECT =
  'slug, status, support_state, canonical_name, model_name, era, year_released, kg_brand(name)'

/**
 * The two reads the index needs, injected so the loader stays testable without
 * a database — the same shape as `EligibilityFetchers` in `./search-resolver`.
 */
export interface SearchIndexFetchers {
  /** `kg_product` rows in `SEARCH_PRODUCT_SELECT` shape, narrowed to active + supported. */
  productRows: () => Promise<{ data: unknown; error: unknown }>
  /** `{ slug, browse_domain }` rows from `browse_product_projection` for these slugs. */
  domainRows: (slugs: string[]) => Promise<{ data: unknown; error: unknown }>
}

async function readRows(
  read: () => Promise<{ data: unknown; error: unknown }>,
  stage: string,
): Promise<Array<Record<string, unknown>>> {
  let result: { data: unknown; error: unknown }
  try {
    result = await read()
  } catch {
    throw new CatalogueUnavailableError(`${stage}_transport`)
  }
  if (result.error) throw new CatalogueUnavailableError(`${stage}_probe`)
  if (!Array.isArray(result.data)) throw new CatalogueUnavailableError(`${stage}_shape`)
  return result.data.filter(
    (row): row is Record<string, unknown> => row !== null && typeof row === 'object',
  )
}

const text = (value: unknown): string | null => (typeof value === 'string' ? value : null)

/**
 * The product section of the index, from live catalogue state.
 *
 * WHICH ROWS: those `isSupportedMusicProduct()` accepts — the one authority for
 * "supported" (CLAUDE.md §5). The query's own filters only narrow the read;
 * every row is re-decided here, so a fetcher that forgets a filter still cannot
 * widen the index, and a family-label row never becomes a product entity.
 *
 * FAIL-CLOSED. A read that errors, rejects or returns a non-array raises
 * `CatalogueUnavailableError`, which the route answers with 503. It never
 * becomes an empty index, which would tell every visitor that Klup follows
 * nothing. A row whose support or domain axis cannot be read is left out.
 */
export async function loadProductEntities(fetchers: SearchIndexFetchers): Promise<SearchEntity[]> {
  const rows = await readRows(fetchers.productRows, 'search_index_products')
  const slugs = rows.map((row) => text(row.slug)).filter((slug): slug is string => slug !== null)
  if (slugs.length === 0) return []

  const domains = await readRows(() => fetchers.domainRows(slugs), 'search_index_domain')
  const domainBySlug = new Map<string, string | null>()
  for (const row of domains) {
    const slug = text(row.slug)
    if (slug !== null) domainBySlug.set(slug, text(row.browse_domain))
  }

  return rows
    .filter((row) =>
      isSupportedMusicProduct({
        slug: text(row.slug),
        status: text(row.status),
        support_state: text(row.support_state),
        browse_domain: domainBySlug.get(text(row.slug) ?? '') ?? null,
      }),
    )
    .map((row) => productEntity(row as unknown as SearchProductRow))
    .sort((a, b) => (a.slug < b.slug ? -1 : a.slug > b.slug ? 1 : 0))
}

/** The index as the resolver sees it: the caller's products, and live families. */
export function buildSearchIndex(
  products: SearchEntity[],
  families: readonly NavigationFamily[],
): SearchIndex {
  return { products, families: liveFamilyEntities(families) }
}

/** Every entity, products first. Order is stable and slug-deterministic. */
export function allEntities(index: SearchIndex): SearchEntity[] {
  return [...index.products, ...index.families]
}
