/**
 * The restricted-search index.
 *
 * Stage 3 WP-4. See docs/stage-3-v1-decision-and-build-plan.md §8.4.
 *
 * A BUILD-TIME STATIC ARTEFACT covering ALL 48 SUPPORTED IDENTITIES — every
 * matcher-eligible product, public or private — plus the navigation families.
 * Generated by `frontend/scripts/build-search-index.ts` and committed as
 * reviewed code, so autocomplete needs no database round-trip per keystroke.
 *
 * WHY 48 AND NOT THE 14 PUBLIC ONES. An index of only the public cohort makes
 * the ARTEFACT the visibility authority, which means a `qa_only -> public`
 * promotion through the admin seam does nothing until someone remembers to
 * regenerate and redeploy: the product is live, its page answers 200, and
 * search still says Klup does not follow it. Indexing the whole supported
 * cohort and filtering per request moves visibility to the only place that can
 * be current — live catalogue state — so a promotion is searchable on the very
 * next request, with no regeneration and no deploy.
 *
 * WHAT THE INDEX IS NOT. It is not an eligibility authority, and after this
 * change it is emphatically not a visibility one. It decides only WHICH ENTITY
 * A TERM MEANS. Whether that entity may be returned is re-decided per request
 * by the four-axis predicate in `lib/catalogue.ts` (`filterEligibleSlugs`), so
 * the 34 private identities in here can be recognised but never returned.
 * A stale index can therefore fail to recognise a NEWLY SUPPORTED product —
 * which the drift test catches — but can never publish a private one.
 *
 * THEREFORE THIS MODULE IS SERVER-ONLY. It carries the slugs and labels of 34
 * unpublished products. It is imported by `app/api/search/resolve/route.ts`
 * and by the test suite, and by nothing that ships to a browser; the guard
 * below makes an accidental client import fail loudly rather than quietly
 * bundling private catalogue state into a public chunk.
 *
 * FAMILIES ARE READ LIVE FROM REVIEWED CODE. `lib/families.ts` is not a
 * database entity, so a build-time snapshot of it would add a staleness class
 * for no benefit. The generator writes the family section so the artefact
 * matches §8.4, and `loadSearchIndex()` rebuilds that section from
 * `NAVIGATION_FAMILIES` at load time so the two can never disagree. The drift
 * test asserts they are equal.
 */

// The `server-only` package is not a dependency and `frontend/package.json` is
// WP-5-owned, so the guard is written by hand. It runs at module scope: any
// client component that imports this module fails on first evaluation instead
// of shipping 34 private slugs to the browser.
// `globalThis`, not a bare `window`: the root tsconfig compiles this file with
// `lib: ["ES2020"]` and no DOM, so referencing `window` directly adds an eighth
// error to a baseline that is meant to stay at seven.
if (typeof (globalThis as { window?: unknown }).window !== 'undefined') {
  throw new Error(
    'lib/search-index.ts is server-only: it contains unpublished catalogue identities.',
  )
}

import rawIndex from '../data/klup-search-index.json'
import { NAVIGATION_FAMILIES } from './families'
import { modelKey } from './model-key'

export type SearchEntityKind = 'product' | 'family'

export interface SearchEntity {
  kind: SearchEntityKind
  /** `/product/<slug>` for a product, `/family/<slug>` for a family. */
  slug: string
  /** Autocomplete label, carrying its disambiguating qualifier (§8.2). */
  label: string
  brand: string
  /** Accepted navigation aliases, already normalised to model keys. */
  aliasKeys: string[]
}

export interface SearchIndex {
  generatedFrom: string
  products: SearchEntity[]
  families: SearchEntity[]
}

/**
 * Terms that must NEVER auto-navigate, adopted verbatim from the supported-
 * search contract (selection doc §11, build plan §8.2).
 *
 * Stored as model keys so `TR 808`, `TR-808` and `tr808` are one entry. A term
 * is dangerous ON ITS OWN; the same token qualified by a brand is not. That is
 * why `minimoog` is here and `moogminimoog` is not: "Minimoog (brandless)" in
 * the contract means the bare term is ambiguous between the 1970s original and
 * the 2016 Model D reissue, while the brand-qualified form is a real identity.
 *
 * GUARDRAIL G1. `search_resolved.auto_navigated` must read exactly 0 for every
 * term in this set, for the whole release. Any dangerous term that
 * auto-navigates is a P0 correctness bug, asserted as a test rather than
 * watched as a metric.
 */
export const DANGEROUS_TERM_KEYS: ReadonlySet<string> = new Set(
  [
    // bare model families — ambiguous across several catalogue identities
    'juno',
    'jupiter',
    'prophet',
    'rhodes',
    'fenderrhodes',
    'spaceecho',
    'modeld',
    'minimoog',
    'system100',
    // bare model numbers
    '808',
    '909',
    '707',
    '727',
    '606',
    '1176',
    // bare descriptors that name a family, a control or a finish
    'poly',
    'mono',
    'source',
    'spirit',
    'synthesizer',
    'studio',
    'custom',
    'standard',
    'vintage',
    'reissue',
    'clone',
    'type',
    'style',
    // conditional forms, per the contract
    'u87', // "U 87 without Ai" — the Ai is the catalogue identity
    'cl1b', // "CL 1B (brandless)"
    'sp12', // "SP-12 when the page is SP-1200"
    'ms20mini', // "MS-20 qualified by Mini/Kit/FS"
    'ms20kit',
    'ms20fs',
  ].map((term) => modelKey(term)),
)

/**
 * Brand prefixes that must never navigate to another brand's page.
 *
 * `Squier` is Fender's budget line and `Epiphone` is Gibson's; the matcher
 * already refuses those as hard brand-collision rejections
 * (`lib/matching/match-listings.ts`), and navigation must not reintroduce what
 * matching rejects. A query carrying one of these never auto-navigates and
 * never contributes a candidate from the shadowed brand.
 */
export const SHADOW_BRAND_KEYS: ReadonlySet<string> = new Set(
  ['squier', 'epiphone', 'tokai', 'greco', 'burny'].map((term) => modelKey(term)),
)

function familyEntity(family: {
  slug: string
  label: string
  brand: string
  aliases: string[]
}): SearchEntity {
  const aliasSource = [family.label, family.slug.replace(/-/g, ' '), ...family.aliases]
  return {
    kind: 'family',
    slug: family.slug,
    label: family.label,
    brand: family.brand,
    aliasKeys: dedupeKeys(aliasSource),
  }
}

/** Normalise, drop empties, de-duplicate — the alias-key discipline. */
export function dedupeKeys(values: string[]): string[] {
  const out = new Set<string>()
  for (const value of values) {
    const key = modelKey(value)
    if (key.length > 0) out.add(key)
  }
  return Array.from(out).sort()
}

/** The family section, derived from reviewed code rather than the artefact. */
export function liveFamilyEntities(): SearchEntity[] {
  return NAVIGATION_FAMILIES.map(familyEntity)
}

/**
 * The index as the resolver sees it: products from the committed artefact,
 * families from `lib/families.ts`.
 */
export function loadSearchIndex(): SearchIndex {
  const parsed = rawIndex as unknown as SearchIndex
  return {
    generatedFrom: parsed.generatedFrom,
    products: parsed.products ?? [],
    families: liveFamilyEntities(),
  }
}

/** Every entity, products first. Order is stable and slug-deterministic. */
export function allEntities(index: SearchIndex): SearchEntity[] {
  return [...index.products, ...index.families]
}
